### ISSUE TITLE
B-tree: remove: Falscher Tag im Text

### ISSUE THREAD

**Issue by FHees** [PrideNoodles/algowiki-pub#8]
An einer Stelle wird statt einem öffnenden Tag <math> ein schließender verwendet.
siehe Screenshot:

![wrong_tag](https://cloud.githubusercontent.com/assets/12294561/8212471/77532860-150b-11e5-90ef-13cba2fe3311.PNG)

**Comment by karweihe** [comment]
Erledigt

2015-06-17 18:12 GMT+02:00 FHees notifications@github.com:

> An einer Stelle wird statt einem öffnenden Tag <math> ein schließender
> verwendet.
> siehe Screenshot:
> 
> [image: wrong_tag]
> https://cloud.githubusercontent.com/assets/12294561/8212471/77532860-150b-11e5-90ef-13cba2fe3311.PNG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hydranox/algowiki-pub/issues/8.

## 

Prof. Karsten Weihe
Hochschulstr. 10, 64289 Darmstadt, Germany
Phone: +49-6151-16-20870
Fax: +49-6151-16-20873
www.algo.informatik.tu-darmstadt.de
